package com.example.aptExpenses.model;

public class Apartment {

    private int id;
    private String name;
    private String market;
    private int unit_count;
    private int year_built;

    public Apartment(int id, String name, String market, int unit_count, int year_built) {
        this.id = id; // Need to think about this since id will be generated by db
        this.name = name;
        this.market = market;
        this.unit_count = unit_count;
        this.year_built = year_built;
    }

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getMarket() {
        return market;
    }
    public void setMarket(String market) {
        this.market = market;
    }
    public int getUnit_count() {
        return unit_count;
    }
    public void setUnit_count(int unit_count) {
        this.unit_count = unit_count;
    }
    public int getYear_built() {
        return year_built;
    }
    public void setYear_built(int year_built) {
        this.year_built = year_built;
    }
    
}
